### ISSUE TITLE
DBD:Sybase - exec Test case failure due to cs_convert failed (to_numeric(3.2))

### ISSUE THREAD

**Issue by SurendarRajavel** [mpeppler/DBD-Sybase#114]
HI Team,

While testing the dbd sybase few test cases are failing for datatype – Numeric and Decimal. Please let me know if we are missing any sybase lib which does this conversion.

exec.t test case: Decimal binding and Numeric datatype is having issue.

$dbh->do("if object_id('dbitest') is not NULL drop proc dbitest");
$rc = $dbh->do(qq{
create proc dbitest \@one varchar(20), \@two int, \**@three numeric(5,2**), \@four smalldatetime, \@five float output
as
    select \@one, \@two, \@three, \@four
    select * from master..sysprocesses

    return \@two
});

ok(defined($rc), "$rc (create proc)\n");

$sth = $dbh->prepare("exec dbitest \@one = ?, \@two = ?, \@three = ?, \@four = ?, \@five = ? output");
#$rc = $sth->execute("one", 2, 3.2, "jan 1 2001", 5.4);
ok(defined($sth), "prepare dbitest");
$sth->bind_param(1, "one");
$sth->bind_param(2, 2, SQL_INTEGER);
**$sth->bind_param(3, 3.2, SQL_DECIMAL);**
$sth->bind_param(4, "jan 1 2001");
$sth->bind_param(5, 5.4, SQL_FLOAT);
$rc = $sth->execute();

Note: Perl and DBI module was installed already 

- HandleSetErr err='19', errstr='cs_convert: cslib user api layer: external error: An illegal locale pointer was specified in the CS_DATAFMT structure.', state=undef, undef
       cs_convert failed (to_numeric(3.2), type=16, scale=1, precision=3, maxlen=35)
    !! ERROR: -1 'cs_convert: cslib user api layer: external error: An illegal locale pointer was specified in the CS_DATAFMT structure.to_numeric() failed for '3.2'' (err#1)
    <- execute= ( undef ) [1 items] at exec.t line 76

t/base.t ........ ok
t/exec.t ........ 1/25
#   Failed test 'execute dbitest 1'
#   at t/exec.t line 77.

#   Failed test 'exec dbitest 2'
#   at t/exec.t line 82.

#   Failed test 'exec dbitest 3'
#   at t/exec.t line 86.

#   Failed test 'out param 1'
#   at t/exec.t line 88.

#   Failed test 'execute fail mode 1'
#   at t/exec.t line 104.

#   Failed test 'execute fail mode 2'
#   at t/exec.t line 108.

#   Failed test 'execute fail mode 3'
#   at t/exec.t line 117.

#   Failed test 'execute fail mode 4'
#   at t/exec.t line 124.

#   Failed test 'execute fail mode 5'
#   at t/exec.t line 128.

#   Failed test 'execute fail mode 6'
#   at t/exec.t line 132.
# Looks like you planned 25 tests but ran 19.
# Looks like you failed 10 tests of 19 run.
t/exec.t ........ Dubious, test returned 10 (wstat 2560, 0xa00)
Failed 16/25 subtests
t/fail.t ........ 1/12
#   Failed test 'execute w/placeholder'
#   at t/fail.t line 76.
# Looks like you failed 1 test of 12.
t/fail.t ........ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/12 subtests
t/login.t ....... 1/6 DBD
[Sybase_dbd_failures.txt](https://github.com/mpeppler/DBD-Sybase/files/8711132/Sybase_dbd_failures.txt)
::Sybase::db ping failed: ct_cmd_alloc failed at t/login.t line 32.
t/login.t ....... ok
t/main.t ........ ok
t/multi_sth.t ... ok
t/nsql.t ........ ok
t/place.t ....... 1/19 DBD::Sybase::st execute failed: cs_convert: cslib user api layer: external error: An illegal locale pointer was specified in the CS_DATAFMT structure.to_numeric() failed for '222.333' at t/place.t line 39.

#   Failed test 'insert 1'
#   at t/place.t line 40.
DBD::Sybase::st execute failed: cs_convert: cslib user api layer: external error: An illegal locale pointer was specified in the CS_DATAFMT structure.to_numeric() failed for '2' at t/place.t line 47.

#   Failed test 'insert 2'
#   at t/place.t line 48.
ct_result(ct_dynamic(CS_PREPARE)) returned -205 at /home/UserID/04202022/DBD-Sybase-1.19/blib/lib/DBD/Sybase.pm line 135.
DBD::Sybase::db prepare failed: Server message number=208 severity=16 state=1 line=1 server=DS_CTO procedure=DBD2 text=#t not found. Specify owner.objectname or use sp_help to check whether the object exists (sp_help may produce lots of output).
  at t/place.t line 56.

#   Failed test 'prepare 2'
#   at t/place.t line 57.
Can't call method "execute" on an undefined value at t/place.t line 59.
# Looks like your test exited with 255 just after 12.
t/place.t ....... Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 10/19 subtests
t/thread.t ...... skipped: this perl 5.034001 not configured to support iThreads
t/utf8.t ........ ok
t/xblk.t ........ ok
t/xblob.t ....... ok

Test Summary Report
-------------------
t/exec.t      (Wstat: 2560 Tests: 19 Failed: 10)
  Failed tests:  8-17
  Non-zero exit status: 10
  Parse errors: Bad plan.  You planned 25 tests but ran 19.
t/fail.t      (Wstat: 256 Tests: 12 Failed: 1)
  Failed test:  9
  Non-zero exit status: 1
t/place.t     (Wstat: 65280 Tests: 12 Failed: 3)
  Failed tests:  5, 10, 12
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 19 tests but ran 12.
Files=13, Tests=235,  2 wallclock secs ( 0.05 usr  0.01 sys +  0.65 cusr  0.12 csys =  0.83 CPU)
Result: FAIL
Failed 3/13 test programs. 14/235 subtests failed.
make: The error code from the last command is 255.

Env Variables 
UserID@UnixAIX7.1_Server:/home/UserID$ echo $SYBASE
/opt/sybase/sybase15
UserID@UnixAIX7.1_Server:/home/UserID$ echo $SYBASE_OCS
OCS-15_0.32bit
UserID@UnixAIX7.1_Server:/home/UserID$ echo $PERL5LIB
/home/UserID/perl5/opt/uxapps/perl5/lib/:/home/UserID/perl5/opt/uxapps/perl5/lib/site_perl/5.34.1/aix:/home/UserID/perl5/opt/uxapps/perl5/lib/site_perl/5.34.1:/home/UserID/perl5/opt/uxapps/perl5/lib/5.34.1/aix:/home/UserID/perl5/opt/uxapps/perl5/lib/5.34.1

Sybase Lib
UserID@UnixAIX7.1_Server:/opt/sybase/sybase15/OCS-15_0.32bit/lib$ ls -l *.a
-rw-r--r--    1 sybase   sybase       210136 Aug 16 2011  libsybblk.a
-rw-r--r--    1 sybase   sybase       210482 Aug 16 2011  libsybblk_r.a
-rw-r--r--    1 sybase   sybase      1726875 Aug 16 2011  libsybcomn.a
-rw-r--r--    1 sybase   sybase      1762184 Aug 16 2011  libsybcomn_r.a
-rw-r--r--    1 sybase   sybase       154139 Aug 16 2011  libsybcs.a
-rw-r--r--    1 sybase   sybase       162103 Aug 16 2011  libsybcs_r.a
-rw-r--r--    1 sybase   sybase      1209283 Aug 16 2011  libsybct.a
-rw-r--r--    1 sybase   sybase      1216580 Aug 16 2011  libsybct_r.a
-rw-r--r--    1 sybase   sybase      2813610 Aug 16 2011  libsybdb.a
-rw-r--r--    1 sybase   sybase        78323 Aug 16 2011  libsybintl.a
-rw-r--r--    1 sybase   sybase        78249 Aug 16 2011  libsybintl_r.a
-rw-r--r--    1 sybase   sybase      1034819 Aug 16 2011  libsybsrv.a
-rw-r--r--    1 sybase   sybase      1072912 Aug 16 2011  libsybsrv_r.a
-rw-r--r--    1 sybase   sybase       389942 Aug 16 2011  libsybtcl.a
-rw-r--r--    1 sybase   sybase       401065 Aug 16 2011  libsybtcl_r.a
-rw-r--r--    1 sybase   sybase       635380 Aug 12 2011  libsybunic.a
[Sybase_dbd_failures.txt](https://github.com/mpeppler/DBD-Sybase/files/8711144/Sybase_dbd_failures.txt)

**Comment by mpeppler** [comment]
I don't really remember seeing this error before. What version of ASE are you connecting to?
What locale are you using (LC_ALL, LANG, etc) ?

**Comment by mpeppler** [comment]
It seems like the version of perl used in the build (/home/UserID/perl5/opt/uxapps/perl5/bin/perl) might not be the same as the one used for the config?

**Comment by mpeppler** [comment]
It's been ages since I worked on an AIX system - off-hand I don't really know what the issue could be.
One might be if there is some issue with the 32bit vs 64bit of various datatypes in the perl config.

We also see in your build/trace log that other tests fail as well (exec.t, fail.t) and this appears to be related to placeholders for some reason - maybe there's some issue with this macro:

#define LOCALE(s)	((s)->locale ? (s)->locale : locale)

which is used extensively to either use the locale pointer defined for the connection (if it exists), or use a default locale pointer that is allocated for the entire process.

For placeholders and variables the locale structure should be filled in via the ct_describe() call. I'll try to look into this some more, but not sure I can figure out what could be wrong here - as this is not new code in any shape or form :-)
