### ISSUE TITLE
Error on prepare with 1.21

### ISSUE THREAD

**Issue by jegade** [mpeppler/DBD-Sybase#123]
With the latest version 1.21 we are getting an error on the prepare:

Usage: DBD::Sybase::st::_prepare(sth, statement, attribs=Nullsv) at /www/.../local/lib/perl5/x86_64-linux/DBD/Sybase.pm line 135

At the moment we rolled back to 1.20 - We are using DBIxClass

**Comment by mpeppler** [comment]
Sorry, I didn't realize that prepare_cached() takes an extra argument.
