### ISSUE TITLE
Changelog dates

### ISSUE THREAD

**Issue by djnorrisdev** [mpeppler/DBD-Sybase#125]
Our organization has been using DBD::Sybase for at least 12 years. I have hit the bug (that I saw you post about on perl monks in 2015) for no implicit conversion from varchar to usigned int. I figure we're on a version before that bug fix occurred, but I don't know how to see what date each new version was released in the cpan changelog. We are currently on DBD::Sybase v1.14. When was that released, and how can I see dates in your changelog?

**Comment by mpeppler** [comment]
Hello

1.14 was released on 2 October 2011 - you can see this on metacpan by using the "jump to version" drop down.
<img width="337" alt="Screenshot 2023-02-02 at 08 24 20" src="https://user-images.githubusercontent.com/2465869/216270831-0e393027-6897-42f4-8e8a-9519d0c5a93d.png">

To be honest I don't remember if this particular issue was fixed - as you've no doubt noticed I haven't been very active with this project over the last 10 years or so...

**Comment by mpeppler** [comment]
I'm unfortunately not sure if this bug has in fact been fixed - I'm trying to go back and look at the code to refresh my memory...

**Comment by djnorrisdev** [comment]
Thanks for the help and quickly picking this up! After I talk with the team, we’re going to schedule pulling the changes in.
