### ISSUE TITLE
DBD-Sybase does not support asymmetric password encryption

### ISSUE THREAD

**Issue by niggemannmj** [mpeppler/DBD-Sybase#131]
When an ASE server is configured as 'net password encryption reqd' with option 2, it the asymmetric password encryption is required with no fallback to the earlier symmetric password encryption.

My application requires this encrypted password exchange, but the DBD-Sybase does not support it currently. I have made tentative changes to the source code to enable it in dbdimp.c based upon the v1.23 code base and it appears to work for me.

**Comment by mpeppler** [comment]
Hi - I just noticed that you have this:

#if defined(CS_SEC_EXTENDED_ENCRYPTION)
        if (level >= 1) {
          CS_INT extendedEncryption = CS_TRUE;
          CS_INT nonEncryptionRetry = CS_FALSE;


Shouldn't that be strictly greater than 1, so that the extended encryption doesn't always happen when encryption is enabled?

**Comment by mpeppler** [comment]
This is now fixed in version 1.24
