### ISSUE TITLE
Impossible to install DBD::Sybase over carton

### ISSUE THREAD

**Issue by KalessinD** [mpeppler/DBD-Sybase#135]
Hi!

Seems that there is no way to use carton (see module Carton) to install this package.
I didn't find any solution to overpass question to choose mode (see [checkChainedAutoCommit](https://github.com/mpeppler/DBD-Sybase/blob/master/Makefile.PL#L517) method in makefile.PL).

This makefile doesn't support any cpan/cpanm/carton environment variables to pass default anwsers or to switch off the interactive mode.

Could you please to support any possible solution to pass an answer without interactive mode?

Thanks in advance.

P.S.

The current error message in carton log:
```
By default DBD::Sybase 1.05 and later use the 'CHAINED' mode (where available)
when 'AutoCommit' is turned off. Versions 1.04 and older instead managed
the transactions explicitly with a 'BEGIN TRAN' before the first DML
statement. Using the 'CHAINED' mode is preferable as it is the way that
Sybase implements AutoCommit handling for both its ODBC and JDBC drivers.

Use 'CHAINED' mode by default (Y/N) [Y]: -> FAIL Timed out (> 60s). Use --verbose to retry.
-> N/A
-> FAIL No MYMETA file is found after configure. Your toolchain is too old?
-> FAIL Configure failed for DBD-Sybase-1.24. See /home/dchernenko/.cpanm/work/1713377911.67154/build.log for details.
-> FAIL Installing the dependencies failed: Module 'DBD::Sybase' is not installed
-> FAIL Bailing out the installation for /home/dchernenko/ipchain/hg-dev-stand/rais/REPO/core.api/.
```

**Comment by KalessinD** [comment]
Thank you for so fast answer.

So, here is my quick proposal to fix this issue:

```diff
--- Makefile.PL	2024-04-18 17:45:11.774142917 +0300
+++ Makefile.PL	2024-04-18 17:49:37.682150578 +0300
@@ -513,2 +513,7 @@
   my $ans;
+
+  if ( not defined($chained) && ($ENV{PERL_MM_USE_DEFAULT} || $ENV{NONINTERACTIVE_TESTING}) ) {
+    $chained = 'CHAINED'; # set the default value
+  }
+
   if ( defined($chained) ) {
```  

You can read about these environments in `man cpan` or [here](https://perldoc.perl.org/ExtUtils::MakeMaker#PERL_MM_USE_DEFAULT).

**Comment by KalessinD** [comment]
I see that you have other questions in makefile.PL.

So, it would be great to have the same applied patch for them too.

**Comment by KalessinD** [comment]
JIC, to install prl packages via carton

1. install carton itself
```bash
$ apt-get install carton
```
2. create cpanfile
```bash
$ cat cpanfile
requires 'DBD::Sybase';
```
3. install module
```bash
$ carton install
```

**Comment by mpeppler** [comment]
It's been some time, but I've added some env. variable checks that should allow for unattended builds. It's not quite what you had in mind, but if you have a few minutes to look at the pull request that'd be great.

Thanks

Michael
