### ISSUE TITLE
Random incorrect conversions of datetime under ISO_STRICT

### ISSUE THREAD

**Issue by djerius** [mpeppler/DBD-Sybase#136]
DBD::Sybase 1.24
perl 5.38
Sybase 16

Observed with DBD::Sybase compiled against the Sybase libs as well as against freetds

when setting

`$dbh->syb_date_fmt( 'ISO_strict' );`

I am _randomly_ getting illegal values for a column with the given definition and values:

```
name        type                 length            
----------  -------------------- -----------       
start_date  datetime                       8       

> select start_date, datepart(year, start_date) as year, datepart(day, start_date) as day, datepart(hour, start_date) as hour, datepart(minute, start_date) as minute, datepart(second, start_date) as second,  datepart(millisecond, start_date) as ms, datepart(microsecond, start_date) as us from SRbrowse where obsid in (782,806);
 start_date          year        day         hour        minute      second      ms          us         
 ------------------- ----------- ----------- ----------- ----------- ----------- ----------- -----------
 Apr 11 2000 12:04AM        2000          11           0           4           4           0           0
 Jan 23 2000  7:46AM        2000          23           7          46           5           0           0
```

Where

`Apr 11 2000 12:04AM` is converted to `2000-04-11T00:04:04.-1026524Z`

and

`Jan 23 2000  7:46AM` is converted to `2000-01-23T07:46:05.-1302389Z`

I've downgraded to 1.23 and haven't seen this repeated.

**Comment by djerius** [comment]
I've added some diagnostics, and the incorrect fractions of seconds seems to be constant per run, e.g. when the wrong value is returned, it's being returned for every returned value (here's a few rows of thousands):

```
2018-08-03T11:41:37.-966379Z
2018-08-24T18:51:02.-966379Z
2019-01-25T03:20:26.-966379Z
2019-07-15T00:03:29.-966379Z
2018-07-03T16:05:29.-966379Z
2018-08-08T23:31:26.-966379Z
2018-07-30T22:35:31.-966379Z
2018-10-24T16:27:16.-966379Z
2018-10-27T06:50:52.-966379Z
2018-10-27T14:52:14.-966379Z
```

These all have zero seconds, so it looks like a variable isn't being initialized to zero properly.

**Comment by djerius** [comment]
> These all have zero seconds, so it looks like a variable isn't being initialized to zero properly.

Sorry, that should be "zero _milli- and micro- seconds_".

**Comment by djerius** [comment]
More debugging on the C side; `rec.datesecprec` is **not** always zero for `CS_DATETIME_TYPE;` in one run it was 32654. From the _Common Libraries Reference Manual_

> &lt;datesecprec> is the precision. For CS_BIGDATETIME and CS_BIGTIME, this
> field is always 10<sup>6</sup>. This field is used only with datetime datatypes having a level of
> precision greater than millisecond
> 

`CS_DATETIME_TYPE` doesn't have that precision, and it looks like the library doesn't initialize the `datesecprec` slot in the structure if it isn't used.

This patch seems to fix it for me:

```
diff -ru DBD-Sybase-1.24.orig/dbdimp.c DBD-Sybase-1.24/dbdimp.c
--- DBD-Sybase-1.24.orig/dbdimp.c	2024-03-24 03:56:51.000000000 -0400
+++ DBD-Sybase-1.24/dbdimp.c	2024-10-01 18:05:58.703371818 -0400
@@ -5346,7 +5346,7 @@
     /* Issue 130 - cs_dt_crack on bigdatetime does not set datemsecond - instead if fills
        datesecfrack */
 #if defined(CS_BIGDATETIME_TYPE)
-    if (rec.datesecprec > 0) {
+    if (srcfmt->datatype == CS_BIGDATETIME_TYPE && rec.datesecprec > 0) {
       rec.datemsecond = rec.datesecfrac / 1000;
     }
 #endif
@@ -5435,7 +5435,7 @@
     /* Issue 130 - cs_dt_crack on bigdatetime does not set datemsecond - instead if fills
        datesecfrack */
 #if defined(CS_BIGTIME_TYPE)
-    if (rec.datesecprec > 0) {
+    if (srcfmt->datatype == CS_BIGTIME_TYPE && rec.datesecprec > 0) {
       rec.datemsecond = rec.datesecfrac / 1000;
     }
 #endif

```

**Comment by mpeppler** [comment]
Thanks - fix committed.

**Comment by djerius** [comment]
Thanks!
