### ISSUE TITLE
exec.t - 'execute fail mode 3' failing [rt.cpan.org #92963]

### ISSUE THREAD

**Issue by mpeppler** [mpeppler/DBD-Sybase#32]
Migrated from [rt.cpan.org#92963](https://rt.cpan.org/Ticket/Display.html?id=92963) (status was 'new')

Requestors:
* sferencik@gmail.com

From https://www.google.com/accounts/o8/id?id=AItOawlVEP5IYeRHpH3ZT4ELVsJ3INWz0Lpegpo on 2014-02-12 12:24:55
:
```
In exec.t, the 'execute fail mode 3' test is failing. I have debugged into it
and I can't see how it could actually be passing for anyone.

I wonder if the expected value of the test shouldn't be *inverted*, i.e. we
should expect the execute to fail rather than to succeed.

Here is what I see happening:

    0001    $sth->{syb_do_proc_status} = 1;
    0002    $dbh->{syb_flush_finish} = 0;
    0003    # ...
    0004    $rc = $sth->execute("raise", 1, 3.2234, "jan 3 2001", 5.4);
    0005    # ...
    0006    get_all_results($sth);
    0007    $rc = $sth->execute(undef, 0, 3.2234, "jan 3 2001", 5.4);

In line 4 we call the dbitest procedure. It returns the value of @two, which in
this case is 1. This means an error state for the procedure. Of course,
execute() itself succeeds, as described in the DBD-Sybase docs for
syb_do_proc_status, but we then proceed to fetch all the results (line 6), and
the last fetch returns the non-zero return status of dbitest().

This non-zero return status is fetched in st_next_result. We then check that
  restype == CS_PARAM_RESULT (== 4042)
and set the failFlag. Then, based on the failFlag, we call syb_st_finish(). Yes,
this actually finishes the $sth. As a result, the subsequent call to execute
(line 7) refuses to ct_send.

My question is: should we

A) rebase the test, expecting the execute on line 7 to fail?

B) try to fix this in DBD-Sybase so that we don't finish the statement handle?

Any comments welcome.

Thanks,
Sam


```

**Comment by mpeppler** [comment]
Interesting - obviously this test does NOT fail with Sybase libs and a Sybase server. I'll take a deeper look in the coming days.

**Comment by mpeppler** [comment]
I've gone back and looked at the code - takes a while, I haven't looked at this seriously in 10 years...

The call to $sth->execute() that fails with FreeTDS actually succeeds with Sybase OpenClient.
The call to execute() calls _dbd_rebind_ph() to bind the parameters to the call - but because this is an RPC call we first ct_command(CS_RPC_CMD) which in effect re-initializes the call and resets the $sth to being active.
I don't really see any reason to change this behavior at this point, but I'm open to arguments.

**Comment by sferencik** [comment]
It's been years for me too. Thanks for checking! Maybe it's a test that should be skipped for FreeTDS, but I don't remember if there's a way to determine if FreeTDS is being used.

**Comment by sferencik** [comment]
Maybe you can detect FreeTDS and/or MS SQL using
```
$dbh->{syb_server_version} ne 'Unknown'
```
as per #39.

**Comment by mpeppler** [comment]
The issue was with FreeTDS - tested and fixed in the latest commit.
